### ISSUE TITLE
future proofing sphp with semver and self-update

### ISSUE THREAD

**Issue by jameswilson** [rhukster/sphp.sh#2]
First of all, thanks for this useful script!

I found instructions to install it ([via](https://getgrav.org/blog/macos-ventura-apache-multiple-php-versions)):

```sh
curl -L https://raw.githubusercontent.com/rhukster/sphp.sh/main/sphp.sh > /usr/local/bin/sphp
chmod +x /usr/local/bin/sphp
```

But when php 8.2+ comes out (assuming this script would be maintained and updated), I'll have to go figure out again where to grab the latest version.  And I noticed a few improvements that could be made to this respect

1. the README should contain install/update instructions.
2. there isn't any mention inside the sphp.sh file itself about where it came from or what version it is.
3. it would be amazing if there could be a self-update sub-command.

**Comment by rhukster** [comment]
Updated README.md with some simple instructions
